theme: jekyll-theme-minimal

title: coding.care
description: every dissertation starts somewhere | bless this mess 
author: Sarah Ciston

logo: 'assets/img/goingonline.jpg'
# show_downloads: 
# google_analytics: 

baseurl: /codingcare

links: 
  # "Get this dissertation in your Inbox (TK)":
    # - "mailgun-setup-TK"
  "Intersectional AI Toolkit": 
    - "https://intersectionalai.com"
  "Tethered.Network": 
    - "https://sarahciston.github.io/tethered"
  "Get your pal a QUEER LOVE zine": 
    - "https://queerlovezine.com/"
  # "Get yourself a shirt":
    # - "https://www.bonfire.com/store/coding-care/"
  "More projects": 
    - "https://sarahciston.com"
links_new_tab: true

markdown: kramdown
kramdown:
  parse_block_html: true
  toc_levels: "2"

# how do i indicate other folders to include in jekyll conversion again

github: [metadata]

plugins:
  - jekyll-spaceship

# Where things are
jekyll-spaceship:
  # default enabled processors
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
  mathjax-processor:
    src:
      - https://polyfill.io/v3/polyfill.min.js?features=es6
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    config:
      tex:
        inlineMath:
          - ['$','$']
          - ['\(','\)']
        displayMath:
          - ['$$','$$']
          - ['\[','\]']
      svg:
        fontCache: 'global'
    optimize: # optimization on building stage to check and add mathjax scripts
      enabled: true # value `false` for adding to all pages
      include: []   # include patterns for math expressions checking (regexp)
      exclude: []   # exclude patterns for math expressions checking (regexp)
  plantuml-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: plantuml
    syntax:
      code: 'plantuml!'
      custom: ['@startuml', '@enduml']
    src: http://www.plantuml.com/plantuml/svg/
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid!'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/
  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 350
      frameborder: 0
      style: 'max-width: 600px; outline: none;'
      allow: 'encrypted-media; picture-in-picture'
  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/

