theme: jekyll-theme-minimal

title: coding.care
description: every dissertation starts somewhere | bless this mess 


# logo: 
# show_downloads: 
# google_analytics: 

links: 
  "Get this dissertation in your Inbox (TK)":
    - "TK"
  "Intersectional AI Toolkit": 
    - "https://sarahciston.github.io/intersectionalai"
  "Tethered.Network": 
    - "https://sarahciston.github.io/tetherednetwork"
  "Get your pal a QUEER LOVE zine": 
    - "https://queerlovezine.com/"
  "Get yourself a shirt":
    - "https://www.bonfire.com/store/coding-care/"
  "More projects": 
    - "https://sarahciston.github.io"
links_new_tab: true


