theme: jekyll-theme-minimal

title: coding.care
description: every dissertation starts somewhere | bless this mess 
author: Sarah Ciston

# logo: 
# show_downloads: 
# google_analytics: 

links: 
  # "Get this dissertation in your Inbox (TK)":
    # - "mailgun-setup-TK"
  "Intersectional AI Toolkit": 
    - "https://sarahciston.github.io/intersectionalai"
  "Tethered.Network": 
    - "https://sarahciston.github.io/tethered"
  "Get your pal a QUEER LOVE zine": 
    - "https://queerlovezine.com/"
  # "Get yourself a shirt":
    # - "https://www.bonfire.com/store/coding-care/"
  "More projects": 
    - "https://sarahciston.github.io"
links_new_tab: true

# how do i indicate other folders to include in jekyll conversion again

## prose.io config
prose:
  rooturl: 'posts'
  siteurl: 'https://sarahciston.github.io/sarahciston/codingcare'
  media: 'assets/img'
  metadata:
    posts:
      - name: "layout"
        field: 
          element: "select"
          value: "default"
          options: 
            - name: "default"
              value: "default"
            - name: "post"
              value: "post"
            - name: "page"
              value: "page"
      # - name: "layout"
      #   field: 
      #     element: "hidden"
      #     value: "default"
      - name: "date"
        field:
          element: "text"
          label: "date"
          value: CURRENT_DATETIME
          type: "text"
      - name: "nav_order"
        field:
          element: "number"
          label: "nav_order"
          type: "number"
      - name: "title"
        field:
          element: "text"
          label: "title"
          type: "text"
      - name: "author"
        field: 
          element: "hidden"
          value: CURRENT_USER
    users:
      - login: "sarahciston"
        user: "Sarah Ciston"

