theme: jekyll-theme-minimal

title: coding.care
description: every dissertation starts somewhere | bless this mess 
author: Sarah Ciston

# logo: 
# show_downloads: 
# google_analytics: 

baseurl: /codingcare

links: 
  # "Get this dissertation in your Inbox (TK)":
    # - "mailgun-setup-TK"
  "Intersectional AI Toolkit": 
    - "https://sarahciston.github.io/intersectionalai"
  "Tethered.Network": 
    - "https://sarahciston.github.io/tethered"
  "Get your pal a QUEER LOVE zine": 
    - "https://queerlovezine.com/"
  # "Get yourself a shirt":
    # - "https://www.bonfire.com/store/coding-care/"
  "More projects": 
    - "https://sarahciston.github.io"
links_new_tab: true

# how do i indicate other folders to include in jekyll conversion again

github: [metadata]

